package rest;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@RestController
public class HelloController {
    @RequestMapping("/")
    public String index() {
        return "hello from simple rest";
    }
}
